// This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// DO NOT edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // TODO: Replace with your actual Firebase config values from:
  // Firebase Console → Project Settings → Your Apps
  // ──────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BKBXcdbF_TOJ0-TjhTJz9VLz_t-wEoA',
    appId: '1:723703253854:android:3c04f7b3ea44b79a9e9dcf',
    messagingSenderId: '723703253854',
    projectId: 'heart-beat-1108',
    storageBucket: 'heart-beat-1108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GTPWPEvsbItsf9GShUnLPw8TGnHxcYk',
    appId: '1:723703253854:ios:5570f3c430f6d2869e9dcf',
    messagingSenderId: '723703253854',
    projectId: 'heart-beat-1108',
    storageBucket: 'heart-beat-1108.firebasestorage.app',
    iosBundleId: 'com.heartbeat.musk',
  );

}